/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  CourseMaterial as PrismaCourseMaterial,
  ClassModel as PrismaClassModel,
} from "@prisma/client";

export class CourseMaterialServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.CourseMaterialCountArgs, "select">
  ): Promise<number> {
    return this.prisma.courseMaterial.count(args);
  }

  async courseMaterials(
    args: Prisma.CourseMaterialFindManyArgs
  ): Promise<PrismaCourseMaterial[]> {
    return this.prisma.courseMaterial.findMany(args);
  }
  async courseMaterial(
    args: Prisma.CourseMaterialFindUniqueArgs
  ): Promise<PrismaCourseMaterial | null> {
    return this.prisma.courseMaterial.findUnique(args);
  }
  async createCourseMaterial(
    args: Prisma.CourseMaterialCreateArgs
  ): Promise<PrismaCourseMaterial> {
    return this.prisma.courseMaterial.create(args);
  }
  async updateCourseMaterial(
    args: Prisma.CourseMaterialUpdateArgs
  ): Promise<PrismaCourseMaterial> {
    return this.prisma.courseMaterial.update(args);
  }
  async deleteCourseMaterial(
    args: Prisma.CourseMaterialDeleteArgs
  ): Promise<PrismaCourseMaterial> {
    return this.prisma.courseMaterial.delete(args);
  }

  async getClassField(parentId: string): Promise<PrismaClassModel | null> {
    return this.prisma.courseMaterial
      .findUnique({
        where: { id: parentId },
      })
      .classField();
  }
}
